
package reclutamiento;

import clases.conexion;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static reclutamiento.Inicio.permiso;

/**
 * @author Giuliana Carnevalle, Bautista Venier y Alan Sebastian Schimpf
 */

public class PDFcandidatos extends javax.swing.JFrame {
    
    public int cant = 0;

    /**
     * Creates new form PDFcandidatos
     */
    
    public PDFcandidatos() {
        initComponents();
        
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setResizable(false);                                        //el usuario no puede modificar las dimensiones del jframeform
        setTitle("Candidatos PDF");
        setLocationRelativeTo(null);
    }
    
    @Override
    public Image getIconImage(){                    //cambiamos el icono del jframeform
    
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/iconoVEC.png"));
        return retValue;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        check_nombre = new javax.swing.JCheckBox();
        check_apellido = new javax.swing.JCheckBox();
        check_telefono = new javax.swing.JCheckBox();
        check_email = new javax.swing.JCheckBox();
        check_linkedin = new javax.swing.JCheckBox();
        check_perfil = new javax.swing.JCheckBox();
        check_seniority = new javax.swing.JCheckBox();
        check_nivelingles = new javax.swing.JCheckBox();
        check_rate = new javax.swing.JCheckBox();
        check_cliente = new javax.swing.JCheckBox();
        check_estado = new javax.swing.JCheckBox();
        check_observaciones = new javax.swing.JCheckBox();
        check_fecha = new javax.swing.JCheckBox();
        check_reclutadora = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/flechaatras.jpg"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hogar.jpg"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Candidatos PDF ");

        check_nombre.setText("Nombre");

        check_apellido.setText("Apellido");

        check_telefono.setText("Telefono");

        check_email.setText("Email");

        check_linkedin.setText("Linkedin");

        check_perfil.setText("Perfil");

        check_seniority.setText("Seniority");

        check_nivelingles.setText("Nivel de ingles");

        check_rate.setText("Rate");

        check_cliente.setText("Cliente");

        check_estado.setText("Estado");

        check_observaciones.setText("Observaciones");

        check_fecha.setText("Fecha");

        check_reclutadora.setText("Reclutadora");

        jButton1.setText("Crear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(check_nombre)
                            .addComponent(check_apellido)
                            .addComponent(check_telefono)
                            .addComponent(check_email)
                            .addComponent(check_linkedin)
                            .addComponent(check_perfil)
                            .addComponent(check_seniority))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(check_reclutadora)
                            .addComponent(check_fecha)
                            .addComponent(check_observaciones)
                            .addComponent(check_estado)
                            .addComponent(check_cliente)
                            .addComponent(check_rate)
                            .addComponent(check_nivelingles))))
                .addContainerGap(226, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(71, 71, 71)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(check_nombre)
                    .addComponent(check_nivelingles))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(check_apellido)
                    .addComponent(check_rate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(check_telefono)
                    .addComponent(check_cliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(check_email)
                    .addComponent(check_estado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(check_linkedin)
                    .addComponent(check_observaciones))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(check_perfil)
                    .addComponent(check_fecha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(check_seniority)
                    .addComponent(check_reclutadora))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(78, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        Candidatos newFrame = new Candidatos();
        newFrame.setVisible(true);                                     //hace visible la vantana
        this.dispose();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        if (permiso.equalsIgnoreCase("superadministrador")) {
                        
            SuperAdministrador newFrame = new SuperAdministrador();
            newFrame.setVisible(true);                                     //hace visible la vantana
            this.dispose();
                    
        } else {
                        
            Principal newFrame = new Principal();
            newFrame.setVisible(true);                                     //hace visible la vantana
            this.dispose();
                        
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        if(check_nombre.isSelected()){    cant = cant + 1;   }
        if(check_apellido.isSelected()){    cant = cant + 1;   }
        if(check_telefono.isSelected()){    cant = cant + 1;   }
        if(check_email.isSelected()){    cant = cant + 1;   }
        if(check_linkedin.isSelected()){    cant = cant + 1;   }
        if(check_perfil.isSelected()){    cant = cant + 1;   }
        if(check_seniority.isSelected()){    cant = cant + 1;   }
        if(check_nivelingles.isSelected()){    cant = cant + 1;   }
        if(check_rate.isSelected()){    cant = cant + 1;   }
        if(check_cliente.isSelected()){    cant = cant + 1;   }
        if(check_estado.isSelected()){    cant = cant + 1;   }
        if(check_observaciones.isSelected()){    cant = cant + 1;   }
        if(check_fecha.isSelected()){    cant = cant + 1;   }
        if(check_reclutadora.isSelected()){    cant = cant + 1;   }
        
        Document documento = new Document();

        try {

            String ruta = System.getProperty("user.home");
            PdfWriter.getInstance(documento, new FileOutputStream(ruta + "/Desktop/Candidatos.pdf"));
            
            Paragraph parrafo = new Paragraph();
            parrafo.setAlignment(Paragraph.ALIGN_CENTER);
            parrafo.add("Formato creado por Giuliana Carnevalle, Bautista Venier y Alan Sebastian Schimpf © \n\n");
            parrafo.setFont(FontFactory.getFont("Tahoma", 18, Font.BOLD, BaseColor.DARK_GRAY));
            parrafo.add("Candidatos \n\n");

            documento.open();
            documento.add(parrafo);                                   //agrego el parrafo al documento

            PdfPTable tabla = new PdfPTable(cant);
            
            if(check_nombre.isSelected()){  tabla.addCell("Nombre");    }
            if(check_apellido.isSelected()){    tabla.addCell("Apellido");  }
            if(check_telefono.isSelected()){    tabla.addCell("Telefono");  }
            if(check_email.isSelected()){    tabla.addCell("Email");  }
            if(check_linkedin.isSelected()){    tabla.addCell("Linkedin");  }
            if(check_perfil.isSelected()){    tabla.addCell("Perfil");  }
            if(check_seniority.isSelected()){    tabla.addCell("Seniority");  }
            if(check_nivelingles.isSelected()){    tabla.addCell("Nivel de Ingles");  }
            if(check_rate.isSelected()){    tabla.addCell("Rate");  }
            if(check_cliente.isSelected()){    tabla.addCell("Cliente");  }
            if(check_estado.isSelected()){    tabla.addCell("Estado");  }
            if(check_observaciones.isSelected()){    tabla.addCell("Observaciones");  }
            if(check_fecha.isSelected()){    tabla.addCell("Fecha");  }
            if(check_reclutadora.isSelected()){    tabla.addCell("Reclutadora");  }
            
            for (int i = 0; i < cant; i++) {
                
                tabla.addCell(" ");
                
            }

            try {

                Connection cn = conexion.conectar();
                
                PreparedStatement pst = cn.prepareStatement("select * from candidatos");
                ResultSet rs = pst.executeQuery();
                
                if(rs.next()){
                
                    do {                        
                        
                        if(check_nombre.isSelected()){  tabla.addCell(rs.getString(2));    }
                        if(check_apellido.isSelected()){    tabla.addCell(rs.getString(3));  }
                        if(check_telefono.isSelected()){    tabla.addCell(rs.getString(4));  }
                        if(check_email.isSelected()){    tabla.addCell(rs.getString(5));  }
                        if(check_linkedin.isSelected()){    tabla.addCell(rs.getString(6));  }
                        if(check_perfil.isSelected()){    tabla.addCell(rs.getString(7));  }
                        if(check_seniority.isSelected()){    tabla.addCell(rs.getString(8));  }
                        if(check_nivelingles.isSelected()){    tabla.addCell(rs.getString(9));  }
                        if(check_rate.isSelected()){    tabla.addCell(rs.getString(10));  }
                        if(check_cliente.isSelected()){    tabla.addCell(rs.getString(11));  }
                        if(check_estado.isSelected()){    tabla.addCell(rs.getString(12));  }
                        if(check_observaciones.isSelected()){    tabla.addCell(rs.getString(13));  }
                        if(check_fecha.isSelected()){    tabla.addCell(rs.getString(14));  }
                        if(check_reclutadora.isSelected()){    tabla.addCell(rs.getString(15));  }
                        
                    } while (rs.next());
                    
                    documento.add(tabla);
                    
                    cant = 0;
                
                }else{
                
                    JOptionPane.showMessageDialog(null, "La tabla esta vacia");
                
                }
                
            } catch (DocumentException | SQLException e) {
                
            }
            
            documento.close();
            JOptionPane.showMessageDialog(null, "Reporte creado");

        } catch (HeadlessException e) {
            
        } catch (FileNotFoundException | DocumentException ex) {
            Logger.getLogger(AgregarCandidato.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PDFcandidatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PDFcandidatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PDFcandidatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PDFcandidatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PDFcandidatos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox check_apellido;
    private javax.swing.JCheckBox check_cliente;
    private javax.swing.JCheckBox check_email;
    private javax.swing.JCheckBox check_estado;
    private javax.swing.JCheckBox check_fecha;
    private javax.swing.JCheckBox check_linkedin;
    private javax.swing.JCheckBox check_nivelingles;
    private javax.swing.JCheckBox check_nombre;
    private javax.swing.JCheckBox check_observaciones;
    private javax.swing.JCheckBox check_perfil;
    private javax.swing.JCheckBox check_rate;
    private javax.swing.JCheckBox check_reclutadora;
    private javax.swing.JCheckBox check_seniority;
    private javax.swing.JCheckBox check_telefono;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
